apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
   metadata:
     labels:
       app: kubia
   spec:
     containers:
     - name: kubia
       image: nickjohnsonm/kubia
       ports:
       - name: http
         containerPort: 8080
       - name: https
         containerPort: 8443
